Jenkinsfile
Jenkinsfile was used for describing docker image build job.
=> Add Jenkinsfile for docker image build job

.gitignore, Jenkinsfile
Successfully tested docker build in Sandbox environment: [build](https://jenkins.edgexfoundry.org/sandbox/view/All/job/edgexfoundry/job/edgex-taf-common/view/change-requests/job/PR-9/)
Per the following LF ticket [IT-18472](https://jira.linuxfoundation.org/servicedesk/customer/portal/2/IT-18472) the settings file to use for this project is called: **taf-settings**
Resolves the following issue: https://github.com/edgexfoundry/edgex-taf-common/issues/6
Signed-off-by: Emilio Reyes <emilio.reyes@intel.com>
=> Update Jenkinsfile to use edgeXBuildDocker function

Dockerfile, LICENSE, README.md, TAF-Manager/trigger/run.py, TUC/__main__.py, TUC/trigger.py, requirements.txt, robot-entrypoint.sh, setup.py
Fix #10 
1. Support multiple profiles and aggregate test report
2. Setup python module
=> Support multiple profiles and Setup python module

.gitignore, Dockerfile
Fix https://github.com/edgexfoundry/edgex-taf-common/issues/20
Signed-off-by: Ginny Guan <ginny@iotechsys.com>
=> Update Dockerfile to add curl

Dockerfile, requirements.txt, setup.py
Add robotframework-seleniumlibrary and install webdriver for chrome.
=> Add selenium library and webdriver for WebGUI test

Dockerfile
Fix #26
Signed-off-by: Ginny Guan <ginny@iotechsys.com>
=> add openssl to Dockerfile

Dockerfile, requirements.txt, setup.py
=> Add redis package to use redis pubsub

Dockerfile
=> Change the robotframework-seleniumlibrary version to 5.1.3

Dockerfile, requirements.txt
Signed-off-by: Ginny Guan <ginny@iotechsys.com>
=> Fix install RESTinstance error and add pyzmq

Dockerfile
Add database library and dependencies.
Upgrade some libraries version, because of the alpine 3.15. 
=> Add database library and dependencies

Dockerfile
Fix #43 
1. Add pycryptodome library
2. Update dockerhub and alpine version
3. Update some library versions dependents on alpine 3.16
=> Add pycryptodome library and update some library's version

Dockerfile, requirements.txt
fix #46 
Signed-off-by: melody <melody@iotechsys.com>
=> feat: add influxdb-client library

Dockerfile
Related [edgex-taf PR#789](https://github.com/edgexfoundry/edgex-taf/pull/789)
=> fix: Add jq library for get token

Dockerfile, requirements.txt
=> refactor: Update redis version to 4.5.3

.github/dependabot.yml, Dockerfile
=> fix: Add dependabot.yml file to custom dependabot configuration and update Dockerfile to use requirements.txt

requirements.txt
=> fix: Upgrade redis and requests library version

.github/dependabot.yml
=> fix: Update dependabot schedule interval to monthly

Dockerfile, requirements.txt
Update alpine version for upgrading chromedriver version
=> Upgrade alpine version

requirements.txt
=> fix: Add libraries for generating external jwt token

TUC/report/ColorLog.py, requirements.txt
=> fix: Update ColorLog.py to log correctly
